services:

  zipkin:
    image: openzipkin/zipkin:latest
    mem_limit: 800m
    ports:
      - "9411:9411"
    networks:
      - booking-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    mem_limit: 800m
    command: start-dev
    ports:
      - "8087:8080"
    networks:
      - booking-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  configserver:
    image: maxi1234/config:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - booking-network
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  eurekaserver:
    image: maxi1234/discovery:latest
    mem_limit: 800m
    ports:
      - "8065:8065"
    networks:
      - booking-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  hotels:
    image: maxi1234/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - booking-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  reservations:
    image: maxi1234/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - booking-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  rooms:
    image: maxi1234/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - booking-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  gatewayserver:
    image: maxi1234/gatewayserver:latest
    mem_limit: 800m
    ports:
      - "8086:8086"
    networks:
      - booking-network
    depends_on:
      - configserver
      - eurekaserver
      - hotels
      - rooms
      - reservations
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

networks:
  booking-network:
