services:
  configserver:
    image: maxi1234/config:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - booking-network

  hotels:
    image: maxi1234/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - booking-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085

  reservations:
    image: maxi1234/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - booking-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085

  rooms:
    image: maxi1234/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - booking-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/


networks:
  booking-network:
