services:

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 800m
    ports:
      - "9411:9411"
    networks:
      - booking-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    mem_limit: 800m
    command: start-dev
    ports:
      - "8087:8080"
    networks:
      - booking-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  configserver:
    image: maxi1234/config:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - booking-network

  eurekaserver:
    image: maxi1234/discovery
    mem_limit: 800m
    ports:
      - "8065:8065"
    networks:
      - booking-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085

  hotels:
    image: maxi1234/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - booking-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/


  reservations:
    image: maxi1234/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - booking-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/


  rooms:
    image: maxi1234/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - booking-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/


networks:
  booking-network:
